environment: production
chdir: /home/root/push_app/current
address: 127.0.0.1
user: root
group: root
port: 3500
pid: /home/root/push_app/current/tmp/thin.pid
rackup: /home/root/push_app/current/config.ru
log: /home/root/push_app/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
