environment: production
chdir: ./
address: 0.0.0.0
user: root
group: root
port: 3500
pid: ./tmp/pids/thin.pid
rackup: ./config.ru
log: ./log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
